production:
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  database: angram_development
  pool: 5
  host: localhost
  username: jason
  password: D1ckn0s3

test:
  adapter: postgresql
  database: anagram_test
  pool: 5
  host: localhost
  username: jason
  password: D1ckn0s3