#config/database.yml
production:
  url: <%= ENV['postgres://mjnfeymrvpcaqz:Z3UlI4xBAo2LJzDv8mlYImcmDy@ec2-54-235-145-226.compute-1.amazonaws.com:5432/d6cequgr2tao7h'] %>

development:
  adapter: postgresql
  database: angram_development
  pool: 5
  host: localhost
  username: jason
  password: D1ckn0s3
    
test:
  adapter: postgresql
  database: anagram_test
  pool: 5
  host: localhost
  username: jason
  password: D1ckn0s3